In [2]:
import numpy as np

In [109]:
data = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
a.dtype

dtype('int32')

In [116]:
a.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
a[0][1]

2.0

In [118]:
a[0]

array([1., 2., 3.], dtype=float32)

In [119]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [125]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [132]:
np.nan + 10

nan

In [137]:
a[0][1] = np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [139]:
a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
a[0][1] = np.nan
a

ValueError: cannot convert float NaN to integer

In [143]:
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [146]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [148]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [150]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [153]:
a = np.array(1)
a
a.shape
a.ndim

0

In [155]:
a = np.array([1])
a
a.shape
a.ndim

1

In [162]:
a = np.array([[1,2,3],[4,5,6]])
a
a.shape
a.ndim

2

In [163]:
a= np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [164]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [165]:
d= np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [166]:
e = np.zeros([3,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [168]:
f = np.empty([2,3])
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [169]:
g = np.full((3,4), 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [ ]:
#집계함수

In [3]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [5]:
a[0,1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [6]:
np.mean(a) #평균

114.4

In [7]:
np.median(a) #중앙값

6.5

In [8]:
np.std(a) #표준편차

296.5485457728633

In [9]:
np.var(a) #분산

87941.04

In [10]:
np.sum(a)

1144

In [11]:
sum(a)

array([ 105, 1006,    9,   11,   13])

In [12]:
np.sum(a,axis=0)

array([ 105, 1006,    9,   11,   13])

In [13]:
np.sum(a,axis=1)

array([1109,   35])

In [14]:
np.max(a)

1000

In [15]:
np.min(a)

2

In [16]:
#Pandas

In [17]:
import pandas as pd

In [22]:
data = np.arange(0,50,10)
data

array([ 0, 10, 20, 30, 40])

In [23]:
a = pd.Series(data, index =['a','b','c','d','e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [24]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [25]:
a['b']

10

In [26]:
a.loc['b'] #명시한 인덱스가 나온다.

10

In [27]:
a.iloc[1] #순서

10

In [28]:
#산술연산

In [29]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [36]:
a+10
a-10
a*10
a**2
a/5
a//5
a%3

a    0
b    1
c    2
d    0
e    1
dtype: int32

In [37]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [38]:
a>15 #15보다 큰 a를 참, 거짓 형태로

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [39]:
a[a>15] #15보다 큰 a가 무엇인지 궁금할때

c    20
d    30
e    40
dtype: int32

In [41]:
##집계함수

In [42]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int32

In [43]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int32

In [44]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int32

In [45]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [46]:
a.mod(3)

a    0
b    1
c    2
d    0
e    1
dtype: int32

In [47]:
a.min()

0

In [48]:
#DataFrame

In [51]:
rawData = np.random.randint(50,100, size=(4,3))
rawData

array([[67, 71, 87],
       [98, 92, 79],
       [51, 75, 99],
       [88, 75, 68]])

In [96]:
df = pd.DataFrame(rawData,
                  index = ['1반', '2반', '1반', '2반'],
                 columns = ['국', '영', '수'])
df

국   영   수
1반  67  71  87
2반  98  92  79
1반  51  75  99
2반  88  75  68

In [53]:
#df[0] -> Error
df['국']

1반    67
2반    98
1반    51
2반    88
Name: 국, dtype: int32

In [55]:
df

국   영   수
1반  67  71  87
2반  98  92  79
1반  51  75  99
2반  88  75  68

In [58]:
df['평균'] = round((df['국']+ df['영']+ df['수'])/3, 2)
df

국   영   수     평균
1반  67  71  87  75.00
2반  98  92  79  89.67
1반  51  75  99  75.00
2반  88  75  68  77.00

In [59]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  67  71  87  75.00 NaN
2반  98  92  79  89.67 NaN
1반  51  75  99  75.00 NaN
2반  88  75  68  77.00 NaN

In [60]:
del df['na']

In [91]:
df

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
2반  88.0  75.0   NaN

In [62]:
df[df. 평균 > 75]

국   영   수     평균
2반  98  92  79  89.67
2반  88  75  68  77.00

In [67]:
df = df.drop(['평균'], axis = 'columns')
df

국   영   수
1반  67  71  87
2반  98  92  79
1반  51  75  99
2반  88  75  68

In [68]:
#결측값 처리

In [97]:
df = df.astype('float')
df

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
1반  51.0  75.0  99.0
2반  88.0  75.0  68.0

In [98]:
df['수'][2] = np.nan
df

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
1반  51.0  75.0   NaN
2반  88.0  75.0  68.0

In [100]:
 df.dropna(axis=0)  #원본을 삭제하진 않음 
    #df.dropna(axis=0, inplace=True) #원본까지 삭제함

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
2반  88.0  75.0  68.0

In [101]:
df

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
1반  51.0  75.0   NaN
2반  88.0  75.0  68.0

In [102]:
 df.dropna(axis=1)


국     영
1반  67.0  71.0
2반  98.0  92.0
1반  51.0  75.0
2반  88.0  75.0

In [104]:
df.fillna('hello')

국     영      수
1반  67.0  71.0   87.0
2반  98.0  92.0   79.0
1반  51.0  75.0  hello
2반  88.0  75.0   68.0

In [105]:
df.fillna(df.mean())

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
1반  51.0  75.0  78.0
2반  88.0  75.0  68.0

In [106]:
#MultiIndex

In [107]:
df

국     영     수
1반  67.0  71.0  87.0
2반  98.0  92.0  79.0
1반  51.0  75.0   NaN
2반  88.0  75.0  68.0

In [108]:
df.T #Column과 Row의 값을 뒤바꿔주는 것

1반    2반    1반    2반
국  67.0  98.0  51.0  88.0
영  71.0  92.0  75.0  75.0
수  87.0  79.0   NaN  68.0

In [109]:
df.index = [['1학년','1학년','2학년','2학년'],['1반','2반','1반','2반']]
df

국     영     수
1학년 1반  67.0  71.0  87.0
    2반  98.0  92.0  79.0
2학년 1반  51.0  75.0   NaN
    2반  88.0  75.0  68.0

In [115]:
df.columns = [['언어', '언어', '수리'], ['국', '영', '수']]
df

언어          수리
           국     영     수
1학년 1반  67.0  71.0  87.0
    2반  98.0  92.0  79.0
2학년 1반  51.0  75.0   NaN
    2반  88.0  75.0  68.0

In [117]:
df['언어']['국']

1학년  1반    67.0
     2반    98.0
2학년  1반    51.0
     2반    88.0
Name: 국, dtype: float64

In [118]:
df.iloc[0]

언어  국    67.0
    영    71.0
수리  수    87.0
Name: (1학년, 1반), dtype: float64

In [119]:
df.loc['1학년']. loc['1반']

언어  국    67.0
    영    71.0
수리  수    87.0
Name: 1반, dtype: float64

In [120]:
#데이터 사전 분석

In [121]:
df

언어          수리
           국     영     수
1학년 1반  67.0  71.0  87.0
    2반  98.0  92.0  79.0
2학년 1반  51.0  75.0   NaN
    2반  88.0  75.0  68.0

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 384.0+ bytes


In [123]:
df.head()

언어          수리
           국     영     수
1학년 1반  67.0  71.0  87.0
    2반  98.0  92.0  79.0
2학년 1반  51.0  75.0   NaN
    2반  88.0  75.0  68.0

In [124]:
df.tail()

언어          수리
           국     영     수
1학년 1반  67.0  71.0  87.0
    2반  98.0  92.0  79.0
2학년 1반  51.0  75.0   NaN
    2반  88.0  75.0  68.0

In [125]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [126]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   76.000000  78.250000  78.000000
std    21.087121   9.358597   9.539392
min    51.000000  71.000000  68.000000
25%    63.000000  74.000000  73.500000
50%    77.500000  75.000000  79.000000
75%    90.500000  79.250000  83.000000
max    98.000000  92.000000  87.000000

In [129]:
#결측치 여부 확인
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [130]:
#값의 연결

In [131]:
a= pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [134]:
b = pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int32

In [135]:
pd.concat([a,b], axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [136]:
pd.concat([a,b], axis=1, ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [138]:
a.append(b,ignore_index=True)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30